### ISSUE TITLE
Log to stderr if record.time is undefined

### ISSUE THREAD

**Issue by kumar303** [willdurand/pino-mozlog#3]
if `record.time` is `undefined` in `createTransformFunction()`, it looks like the message will be lost forever.

https://github.com/willdurand/pino-mozlog/blob/bfa9ee277e2cc82b4d73ba1117f7c19706688fd0/src/index.js#L61

Can this grow an else branch that logs the record to `stderr` as if an error was thrown? Or maybe just throw an error?

**Comment by willdurand** [comment]
Yes, we should definitely log it to `stderr` to be consistent in `--debug` mode. It should never occur because we receive pino logs as input, which has a rather strict schema.

**Comment by kumar303** [comment]
> It should never occur...

riiiiight
